### ISSUE TITLE
relocate rain radar one level up

### ISSUE THREAD

**Issue by RelevanterUsername** [poetaster/harbour-dwd#11]
Currently the rain radar is located in the pulley menu in the day view. This doesn't really make sense, because there is only one rain radar instance available, and not one for each day, and it also implies that I have to scroll to the top in order to open it.
In my opinion it would be more natural and also more accessible to put the rain radar into the pulley menu in the locations week overview.

**Comment by poetaster** [comment]
Yes, this sounds correct to me.

**Comment by poetaster** [comment]
I've moved it to the weekly overview. Still haven't got the lat/lon parameter passing working, but I'll consider this finished.
