### ISSUE TITLE
restyle location view

### ISSUE THREAD

**Issue by DerDakon** [poetaster/harbour-dwd#3]
I would restyle the location view to look more like the builtin notes application.

* have "tiles" for the locations
* show the short weather info on the tiles as shown on the cover view
* use long press and context menu for delete action
* use remorse timer for deletion
* allow to star one location (see #1)

**Comment by poetaster** [comment]
I'm still working out some details since I'm rebuilding the loading and storage of locations. There are about 20,000 stations and I'm currently only fetching a subset, which is not enough. I may make a new ticket that then covers some of this territory.

I'm trying to avoid doing to much geo-location math but it's also a question of storage, etc. So, it's in the works, too ;)

**Comment by DerDakon** [comment]
It's not the "search location" page I'm talking about here, but the one where you end up right after application start if you already have locations configured.

**Comment by poetaster** [comment]
Yeah, I got that. The point I was making is that the information that is available and how it is obtained impose limits on what you can do on the first page. 

At the moment all the data is loaded over the wire, and even with json as the format, loading from multiple locations takes time, and can lead to rendering delays. 

So, if I have, say, six locations stored and I want to show current weather in all of them on the first page, this will cause that page to update in fits and starts. The second view, which show the next 5 days at location FOO ist actually quite slow to load for this reason and I have to use a timer object to make sure all days load in order. 

But, it's good idea. I just need to:
1. Get all locations listed
2. Optimize the loading of daily data from location. 

Then I can get more ambitious with the location overview page.

**Comment by poetaster** [comment]
Ok, I've gone part way. The locations are now remorse enabled list items and the 'last selected' locations data is shown on the same 'start' page.
